plugin: aws_ec2
regions:
  - us-east-1

filters:
  tag:Name:
    - "Jenkins-Server"
  instance-state-name: [running]

hostnames:
  - ip-address
compose:
  ansible_host: public-ip-address
key_groups:
  - key: tags
    prefix: tag

